stages:
  - Build

ros1:
  stage: Build
  trigger:
    include: docker/.gitlab-ci-ros1.yml
    strategy: depend

ros2:
  stage: Build
  trigger:
    include: docker/.gitlab-ci-ros2.yml
    strategy: depend