include:
  - remote: 'https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml'

variables:
  BASE_IMAGE: rwthika/ros2:humble
  COMMAND: ros2 launch carla_its_converter carla_its_converter.launch.py
  TARGET: dev
  PLATFORM: amd64
  IMAGE_TAG: ros2
  ENABLE_INDUSTRIAL_CI: 'true'
  ENABLE_PUSH_AS_LATEST: 'true'