include:
  - project: fb-fi/ops/docker-ros
    ref: main
    file: templates/.gitlab-ci.template.yml

variables:
  DISABLE_ARCH_ARM64: 'true'
  DOCKER_COMPOSE_FILE: docker-compose-ros1.yml
  IMAGE_DEV_TARGET: ${CI_REGISTRY_IMAGE}:ros1-dev
  IMAGE_RUN_TARGET: ${CI_REGISTRY_IMAGE}:ros1