name: consistency

on:
  push:
  workflow_dispatch:

jobs:
  consistency:
    uses: openads-project/openads-dev-environment/.github/workflows/consistency.yml@main
    secrets: inherit
    inputs:
      skip-checks: ros_pubsub_topics_private_namespace
